### PR TITLE
Fixing charset

### PR DESCRIPTION
**Pull request by sergeevabc**
Dear @atoponce,
There is something wrong with the output of Russian diceware.
It seems the wordlist from Arnold Reinhold’s [page][1] was transcoded incorrectly. 
```
for example
землЪк эфиоп эрг оргиЪ натЄк жмот
    ^                ^    ^
should be
земляк эфиоп эрг оргия натёк жмот
```

Let’s transcode properly…
```console
$ iconv -f WINDOWS-1251 -t UTF-8 diceware.ru.txt > tmputf8.txt
```
…and bring it into line with your design.
```awk
$ awk '{print $2}' tmputf8.txt > tmputf8words.txt
$ awk 'a{a=a","}{a=a"\047"$1"\047"}END{print a}' tmputf8words.txt > tmputf8row.txt
$ awk '{print "var diceware_ru=["$0"];"}' tmputf8row.txt > diceware_ru.js
```
Done.

[1]: http://world.std.com/~reinhold/diceware.html#Diceware%20in%20Other%20Languages|outline

### CODE REVIEW

**Comment by atoponce** [comment]
Thanks! You don't by chance speak Bulgarian also, do you? :)

**Comment by sergeevabc** [comment]
Your question seems to be related to issue #4. 

Since it was the Russian language that was taught in Bulgarian schools and not vice versa between 1946 and 1989, it is easier to find a Bulgarian who understands Russian. Both languages are Slavic, but from different branches (East and South), it would be comparable to an Anglophone trying to understand any other Germanic language, yet there are similarities as Cyrillic is used. A mere glance suggests not relying too much on ```aspell``` results, but label it as “help wanted” ([like this][1]).

[1]: https://github.com/navossoc/KeePass-Yet-Another-Favicon-Downloader/issues/2

**Comment by atoponce** [comment]
Yeah, I can label it as "help wanted", that's fine.

The original Bulgarian source is 6 image-based PDFs. I've reached out to the creator of the PDFs, and he does not have the source text. So, I used OCR to extract the text out of the image and use aspell-bg to do a "best guess" at spelling. As a non-Bulgarian speaker, it's the best I can do.

That is, until a Bulgarian speaker comes along, and can help clean them up, or the creator of the original PDFs produces a text version.

**Comment by sergeevabc** [comment]
Kudos for paying attention to [other languages][1] used on the Internet.

[1]: https://en.wikipedia.org/wiki/Languages_used_on_the_Internet

**Pull request merged**
